// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiZrKTQP2oWJUjZJ7zWNKnZClYFttnSIE',
    appId: '1:340862163668:web:bc3d905ab5e8a34b37b941',
    messagingSenderId: '340862163668',
    projectId: 'trabalhomeupai',
    authDomain: 'trabalhomeupai.firebaseapp.com',
    storageBucket: 'trabalhomeupai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaOKXk5MQcpmTy8lGJnUUvpiFG0mawNDc',
    appId: '1:340862163668:android:6bb401d620e83c0b37b941',
    messagingSenderId: '340862163668',
    projectId: 'trabalhomeupai',
    storageBucket: 'trabalhomeupai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxGKTrxaL7Odkmr-W9x7a_dwOv-syg9O8',
    appId: '1:340862163668:ios:c7b532a5b9460cfe37b941',
    messagingSenderId: '340862163668',
    projectId: 'trabalhomeupai',
    storageBucket: 'trabalhomeupai.firebasestorage.app',
    iosBundleId: 'com.example.distribuidora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxGKTrxaL7Odkmr-W9x7a_dwOv-syg9O8',
    appId: '1:340862163668:ios:c7b532a5b9460cfe37b941',
    messagingSenderId: '340862163668',
    projectId: 'trabalhomeupai',
    storageBucket: 'trabalhomeupai.firebasestorage.app',
    iosBundleId: 'com.example.distribuidora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiZrKTQP2oWJUjZJ7zWNKnZClYFttnSIE',
    appId: '1:340862163668:web:7dbd82c98a44a0b537b941',
    messagingSenderId: '340862163668',
    projectId: 'trabalhomeupai',
    authDomain: 'trabalhomeupai.firebaseapp.com',
    storageBucket: 'trabalhomeupai.firebasestorage.app',
  );
}
